### ISSUE TITLE
Baby Chickens Drops Feathers Continually

### ISSUE THREAD

**Issue by MokahTGS** [GenDeathrow/Hatchery#75] opened 2017-04-01 20:38 UTC
Chickens: 4.3.2
Hatchery 0.2.10
Minecraft: 1.10.2
Forge: 2254
Baby Chickens are dropping feathers continually like a fountain of feathers. Once they become adults the feather dropping returns to normal.

This only happens with baby chickens that are grown in the Hatchery nest. so I don't know if this is a Hatchery issue or just chickens.

**Comment by GenDeathrow** [comment] 2017-04-09 06:40
look into this, Do you have Quark installed?

**Comment by GenDeathrow** [comment] 2017-04-09 06:43
I'm wondering it it has to do with this line?
https://github.com/Vazkii/Quark/blob/1db98672c07a092942c70f2646cffa8ca15cc0fa/src/main/java/vazkii/quark/tweaks/feature/ChickensShedFeathers.java#L41

Quark has a config option for baby chickens drop feathers? "Chicks drop feathers" check if its false or true and get back to me. I dont have time to test this atm.

**Comment by MokahTGS** [comment] 2017-04-09 16:24
We do have quark but feather dropping in disabled in the config.

**Comment by GenDeathrow** [comment] 2017-04-09 16:29
im gone for the day or I would do some testing.. have you removed quark and tested?

**Comment by GenDeathrow** [comment] 2017-04-09 17:06
ill also check make sure my last release branch didnt have an issue I didnt catch.

**Comment by GenDeathrow** [comment] 2017-04-10 16:29
I cant seem to recreate this issue, doesn't seem to be affacted by Quark or Hatchery. Is this a server? any other information you can give. Is there an console information getting printed?

**Comment by MokahTGS** [comment] 2017-04-10 16:38
I'll have to check the console stuff.  This is not a server, its a LAN environment, hosted single player.

**Comment by GenDeathrow** [comment] 2017-04-10 16:49
![image](https://cloud.githubusercontent.com/assets/3720710/24872626/a2cade24-1de3-11e7-9b6b-da429f846cc2.png)

I've tried to recreate it, my hatching eggs, creative eggs,  I'm currently on a LAN. But im getting nothing.

**Comment by MokahTGS** [comment] 2017-04-10 16:51
We put the eggs on the nests under glowstone lamps and when they hatch they spew feathers.

**Comment by GenDeathrow** [comment] 2017-04-10 16:56
Ill check that I misunderstood what you meant. but I didn't see feathers when I hatched. checking now

**Comment by GenDeathrow** [comment] 2017-04-10 17:07
Still nothing.. just checked about 30 nest. Something is doing it

**Comment by Puremin0rez** [comment] 2017-04-10 22:45
My modpack is public that is also experiencing the issue - just keep in mind its 320~ mods so it's quite large.

Mod list:
https://minecraft.curseforge.com/projects/dethemium-modded-edition-2017/relations/dependencies

**Comment by Puremin0rez** [comment] 2017-06-07 06:56
So is it fixed? or are you just closing it because you cannot reproduce it?

**Comment by GenDeathrow** [comment] 2017-06-07 15:09
Closing it cause I can not reproduce it in the mid alone. It's obviously a mod interaction.

**Comment by GenDeathrow** [comment] 2017-06-07 16:06
If you test it with out any other mods and it does this than I'll look at it again. Or if it is a mod and you figgure figure out which one than I'll look at it. I just can't reproduce or have seen this happen.

**Comment by MokahTGS** [comment] 2017-06-07 17:11
I have a mod pack with 1.10.2 and the issue no longer happens.  We do not however know what changed to stop the issue.  If it crops up again, I'll post again, but closing this for now is fine.

**Comment by GenDeathrow** [comment] 2017-07-09 16:55
going to reopen this for now... still have no clue whats causing it though, hatchery doesn't give feather drops unless chickens are in pens, Chickens mod doesn't give feather drops at all, and neither does More chickens, but something isn't playing nice.

**Comment by katubug** [comment] 2017-07-09 18:19
I'm going through in singleplayer and doing just that - testing it with my entire modlist, just adding a handful of mods at a time. I don't have any leads because, to my knowledge, nothing I have modifies chicken drops since I removed ChickenShed. Cyclic was suggested but doesn't seem to be the case.

Here's my process document: https://docs.google.com/document/d/1UpjZXoOOXkFGAXzc3fAT4xLf8I12CTo-uQfUdgk-piI/edit?usp=sharing

**Comment by katubug** [comment] 2017-07-09 19:38
Okay, After about an hour of testing, I haven't come up with anything more solid than what you guys have. It's definitely a multiple mod interaction, because it only happens when I have my full modlist, basically. I haven't been able to reproduce it under circumstances with pared down mods. Hopefully if anyone is interested in doing further testing, the testing/research in my document will be helpful. I need a break.

**Comment by GenDeathrow** [comment] 2017-07-10 04:13
This has been one of the hardest bugs to track down. I appreciate ya doing some heavy testing.

**Comment by GenDeathrow** [comment] 2017-07-10 13:46
Question does this only happen with modded chickens or will it also happen on vanilla chickens? if thats the case what ever mod may be having an issue with the modded chickens.

**Comment by MokahTGS** [comment] 2017-07-10 13:53
When we were having this issue we also had Animania installed.   But like I said the issue stopped and we never knew why.  We have since moved on to 1.11.2 so we can't test anything until it comes to that version.

**Comment by katubug** [comment] 2017-07-10 18:39
The only modded chickens we had were the ones from the Chickens and More
Chickens mod. We hadn't progressed enough to unlock any of the More
Chickens, so I can categorically say they weren't involved for us. We
didn't hatch many, if any, vanilla chicks so I can't say with confidence
whether they were affected. We've had to remove the mod from the server due
to lag issues so I can't do any more testing in that environment.

**Comment by GenDeathrow** [comment] 2017-07-10 20:38
Well wish I could tell ya what it is, but like I said another mod is dropping the feathers. Id be glad to help the other mod dev, or if its something on our end I'll fix it. But since I cant recreate it with just my mod its hard to fix.

**Comment by GenDeathrow** [comment] 2017-11-17 16:06
Closing fir now

**Closed by GenDeathrow** 2017-11-17 16:06 UTC
Labels: What is Happening Here?

**Comment by Wizardon777** [comment] 2017-11-20 13:12
I've found the culprit! the "Tertaqueous" mod has a config for mob drops that messes with the chickens.
just disable it, and everything will work fine!

**Comment by katubug** [comment] 2017-11-20 15:56
I'm not 100% sure, but I'm 80% sure that wasn't the answer for me.
Terraqueous and Quark configs were my first stops.

**Comment by viveleroi** [comment] 2018-07-15 20:56
@Wizardon777 Which config for terraqueous? I'm having this issue and if I don't kill the chicken soon there will be too many drops and the client lags.

I believe you meant the following, under "mobs":

```
# Adds feather moulting
B:enableChickenDropTweaks=false```

Going to try it. Will edit with results.
