### ISSUE TITLE
Chickens still disappearing

### ISSUE THREAD

**Issue by tommy1221** [GenDeathrow/Hatchery#46] opened 2017-01-20 04:17 UTC
if i leave the chunk all my chickens disappear in the nesting pens. i use to be able to right click on the nest with a net and then place them back. now it won't let me do either. acts as if the nesting pen is full.

**Comment by tommy1221** [comment] 2017-01-20 11:45
The latest version.  And it's the only version I have downloaded.  Just started playing your mod 2 days ago.  Thanks for the reply.  Love the mod and don't wanna go back to crops.  Chickens are where it's at.  :)

**Comment by tommy1221** [comment] 2017-01-20 11:46
The latest version.  And it's the only version I have downloaded.  Just started playing your mod 2 days ago.  Thanks for the reply.  Love the mod and don't wanna go back to crops.  Chickens are where it's at.  :)

**Comment by Homarus** [comment] 2017-01-20 13:27
Same issue for me, I updated the skyfactory mod, and I lost chickens, but not all of my chickens. From some type of chickens I lost all of them, but from a few types I lost 2 chickens. 

Its weird, While typing I did go to my "testing" area, and there are all the types of my chickens, but in my "chicken farm" not.

Chickens 4.3.2
Hatchery 0.2.5
More Chickens 1.0.11

If you need more information you can contact me.

**Comment by GenDeathrow** [comment] 2017-01-20 15:18
What kinda system are you guys using? and your not using Sponge to play on are you?

**Comment by Homarus** [comment] 2017-01-20 15:56
I use curse with:
Forge 12.18.3.2215
Java 1.8.0.121 64-bit

**Comment by GenDeathrow** [comment] 2017-01-20 16:08
Very strange.. well the only thing I can think of is that the tile entity doesnt update after it loads. So when it saves it doesnt think it has an entity.  I have an idea of how to fix it.  But not entirely sure if thats the real problem. 

If anything would you guys be willing to test iut a beta version to see if it fixes it?I can have a version later today.

**Comment by tommy1221** [comment] 2017-01-20 16:16
Yes I could test tonight. No I'm not on sponge and I'm on a Mac.  Server is
on a pc.

**Comment by tommy1221** [comment] 2017-01-20 16:17
I am also on forge... Not sure what version at the moment.  I can let you
know when I get home though. Probably should have mentioned that last night

**Comment by GenDeathrow** [comment] 2017-01-21 00:07
If you have curse here is my channel
https://curse.com/invite/AMpRToLaIEqxjYjialQtHA

**Comment by GenDeathrow** [comment] 2017-01-21 08:47
Here is the beta version >>> [LINK](https://dl.dropboxusercontent.com/u/44796802/mod%20work/hatchery-1.10.2-0.2.6_b01.jar)

**Comment by tommy1221** [comment] 2017-01-21 11:37
Thanks man... I'll give it a try when I get home from work.  I'll let you
know.

**Comment by GenDeathrow** [comment] 2017-01-21 15:44
Thanks I hope it works, because I cant think of any other reason it would do this. If this works I can get it out for the next sf3 update

This block has a lot of bad code, and each update I am fixing it. But I almost have to do it slowly because if I outright replace it it will delete all nesting pens. .

**Comment by tommy1221** [comment] 2017-01-22 01:28
so far so good. I've left the game and left the chunk and the chicken did not disappear yet. i did however have to destroy my nests and place them again. which means i lost all my old chickens. :(
ill let you know if the problem comes back. it was a short test but it failed every time before. so this is a good sign.

**Comment by tommy1221** [comment] 2017-01-22 01:49
next ill try a server reset. that did it last time too

**Comment by tommy1221** [comment] 2017-01-22 01:57
reset the server and all is good so far.

**Comment by GenDeathrow** [comment] 2017-01-22 08:46
ok I will be pushing this update some time tomorrow night officially unless you find an issue with it before than. Thank for testing this, as it was hard for me to recreate.

**Comment by GenDeathrow** [comment] 2017-01-23 00:31
Im going to take its working as intended atleast..

**Comment by tommy1221** [comment] 2017-01-23 00:32
So far so good.  I test more tomorrow

**Comment by GenDeathrow** [comment] 2017-01-23 00:34
I have to get an update out tonight.. but I wanted to thank you for testing this for me.

**Comment by GenDeathrow** [comment] 2017-01-25 06:30
this should be fixed

**Closed by GenDeathrow** 2017-01-25 06:30 UTC
