### ISSUE TITLE
Bugs found in 0.3.12

### ISSUE THREAD

**Issue by Ravalli03** [GenDeathrow/Hatchery#86] opened 2017-05-20 17:42 UTC
Loving the new update but found some bugs to help you out.

-When placing a chicken directly to nesting pen with net, the name of chicken stays on the net. If placing anywhere esle, works as intended, ie shows its empty.

-When placing a chicken in a nesting pen, count down to next drop is superfast. Seems to run at normal time after chicken has been in pen for awhile.

-Anytime setting up chcikens, ie, growing, moving, etc there are random egg laying noises in the area. Using a Sound Locator (ender io armor), sounds come from the gound but no chickens around. Even tested it at bedrock level. Restarting clears the random noises.

Hope this helps. Thanks for the great mod!

**Comment by ZephyrWindSpirit** [comment] 2017-05-20 18:03
I personally haven't used a sound locator, but can confirm on 0.3.11 that the name of the chicken is remaining on the net. Looks like the NBT data tags are sticking.

**Comment by GenDeathrow** [comment] 2017-05-20 19:10
Yeah I found the net issue the other day.. seems to happen on servers mainly.  Working on a fix.

The random sounds is prolly because I forgot to set the chickens pos to the nesting pen on placement. 

I'll look into the drop times too..

As far as the clipping.. that's going to happen. If you look at the gotten bottom of prns you'll notice thier their feet sticking though so I can't reduce them unless I want to scale them. Not sure if I want to do that.

**Comment by GenDeathrow** [comment] 2017-05-20 20:10
I'm on mobile so I'll correct my spelling errors later on my computer.

**Comment by Ravalli03** [comment] 2017-05-20 21:04
As for the net naming, I'm playing non server singleplayer. 

After some more testing, the fast countdown to next drop goes back to normal countdown after a restart,
ie 1 min countdown runs at like 30 seconds, (not a bad bug, lol)

Thanks for the quick reply!

**Comment by GenDeathrow** [comment] 2017-05-20 22:49
yeah I think I realized the its single player too.

as far as the count down, it doesn't change a whole lot, technically thats when it just moves items from the chicken over to nesting pen, so it doesn't really break anything, but it could be a sync issue, so I look into it.

**Comment by SnakeFang** [comment] 2017-05-21 01:26
The count down thing is an actual, abusable bug. It's easily noticeable if you take a chicken out of a pen and put her back in the same one a bunch of times. I have a feeling it's caused by the nest pen block not deleting the tile entity when it's broken (because of course minecraft is too god damn lazy to handle that for you). Simple fix, just override breakBlock in NestingPenBlock. First call the same method on super, then call removeTileEntity on the world. See net.minecraft.block.BlockContainer, line 47 (in my mappings at least) for an example. :)

**Comment by GenDeathrow** [comment] 2017-05-21 03:21
Welp thanks for that catch..

**Comment by GenDeathrow** [comment] 2017-05-21 05:39
Should be fixed in build 0.3.13, I realized I didn't fix the sound issue, but I cant spend anymore time on this tonight.

**Closed** 2017-05-22 16:48 UTC

**Comment by Ravalli03** [comment] 2017-05-22 16:51
Thanks for the quick fix, I didn't mean to close the issue , hit the wrong button to comment. I'll leave it closed as you are working on it, but feel free to reopen for tracking reasons, etc
