### ISSUE TITLE
Chickens dying in nesting pens [Skyfactory 3 (v3.0.6)]

### ISSUE THREAD

**Issue by lordtazman** [GenDeathrow/Hatchery#64] opened 2017-02-09 21:13 UTC
They still appear but are highlighted red (as if taking damage), when they are taken out and placed on ground, they keel over dead. In the inventory system there will also be raw chicken meat. I initially thought they were suffocating because of the placement of my EnderIO conduits (I had them connected to the top of the Nesting Pen), but I have since moved the pipes to the back or sides (and bottom for that matter) yet they still die as before. I also wait for them to be fully grown before transferring them with the Animal Net to the Nesting Pens (I was also ruling out when they "grow up" while in the Nesting Pen).

**Comment by GenDeathrow** [comment] 2017-02-09 22:01
Ok its impossible for them to take any damage in pens. The chicken entity is not really in the world.. its stored in a blocks data. And the block renders the chick as a fake entity. Basically they are completely immune to damage of any kind. Obviously something is happening.

What kinda system are you running? Is this a server? is anything printing out in console?

**Comment by GenDeathrow** [comment] 2017-02-09 22:04
Also did you add/remove any mods?

**Comment by lordtazman** [comment] 2017-02-09 23:23
I have added Optifine 1.10.2 HD_U_D6 because my computer isn't the best with AMD Radeon Quad Core HD 7660D. I am running Win10 and 64bit Java allocating 4.5GB of RAM, using FTB launcher (I have had horrible time with Curse launcher because of my poor internet), playing single player (not online server). I didn't check the console at the time, gonna have to check after it happens again. Other than Optifine, no other alterations to/of the mods.

**Comment by GenDeathrow** [comment] 2017-02-10 00:43
Have you tested with out optifine? Optifine changes base classes in vanilla. It doesn't like modded mine craft. I could see it causing the issue with rendering actually. As far as the raw chicken. Nesting pens don't pick items up... it catches the egg dropping  that chickens do.

**Comment by lordtazman** [comment] 2017-02-10 01:14
They were fine and dandy, and then I saved and quit. Went back into my world and this is what I see frequently: 
![2017-02-09_17 43 57](https://cloud.githubusercontent.com/assets/25672498/22809784/dd826fd0-eef1-11e6-80a9-ac2029d8b5b1.png)
I go and snag it:
![2017-02-09_17 47 55](https://cloud.githubusercontent.com/assets/25672498/22809842/34444f96-eef2-11e6-9c15-519f3e99e51b.png)
And it keels over:
![2017-02-09_17 47 58](https://cloud.githubusercontent.com/assets/25672498/22809852/409cf77a-eef2-11e6-917f-010a99c48abe.png)

I will try without optifine to see if that is the issue.
I will also screen capture the WAILA tooltip over non-automated-collecting-of-all-the-things Nesting Pen.

**Comment by GenDeathrow** [comment] 2017-02-12 21:07
any luck removing optifine?

**Comment by lordtazman** [comment] 2017-02-13 19:20
It's still occurring without optifine. If I am the only one with this problem, it probably has to do with my loading or unloading of my world. It only effects a few at a time, I will just deal with it and keep up with a bit of "housekeeping", replacing as needed.

**Comment by GenDeathrow** [comment] 2017-02-13 20:15
yeah I finally got optifine to work on my side, and noticed it had nothing to do with it I extremely confused by this as there is absolutely no reason it should happen. I pushed an update out today on hatchery. you could try updating it. SF3 is getting new update soon too. 

Darkosto is doing some streaming later today about SF3. Today is his late day, I believe he will got live in 2 hours??? cant remember. 

https://www.twitch.tv/darkosto

**Comment by lordtazman** [comment] 2017-02-13 20:35
indeed and noted

The only thing in console I get is this message repeating itself half a dozen times about every 5 minutes or so:

 [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at com.gendeathrow.hatchery.core.waila.HatcheryTileProvider.getNBTData(HatcheryTileProvider.java:145) ~[HatcheryTileProvider.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler$1.run(MessageRequestTile.java:100) ~[MessageRequestTile$Handler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]

There are times when I was transferring the chickens with the net from the hatching nests to the nesting pens, occasionally I would whiff and miss with the net, immediately try again and snag it. The null pointer thing is my only clue. Obviously I know nothing of code and all the above is Greek to me. :(

**Comment by GenDeathrow** [comment] 2017-02-13 21:26
that is HWYLA issue.. you need to update it.

**Comment by jk1895** [comment] 2017-02-19 22:29
I have the same issue! I can take the chicken out an place on the ground. But it's missing a half heart.
I play Sky Factory 3. No changes.
Here you can see 6 chicken "suffering". But I have a lot more of those red chicken.
![2017-02-19_23 09 09](https://cloud.githubusercontent.com/assets/20401451/23107283/98853c3a-f6fa-11e6-8b95-5ccb818b3dc7.png)

In To Asgaards Let's Play you can see this very good (Link with right time stamp):
https://youtu.be/1Cu5YVP1aN8?list=PLqDcvVfNOtHqAWO36nb2GvHiLmH4NKGmk&t=52

**Comment by GenDeathrow** [comment] 2017-02-19 23:37
its because they get hit before they get caught in the net.. and that state gets saved in the nesting pen. I see what I can do. but I would have to find a good situation..  do you guys have an item in the off hand that hits the chickens maybe?

**Comment by jk1895** [comment] 2017-02-19 23:45
No, they had not suffered any harm. I put them healthy in the cage with an empty off hand.

To Asgaard mentioned in another video that this is (maybe) caused by loading and unloading chunks. But unfortunately I can't find this passage.

**Comment by jk1895** [comment] 2017-02-19 23:52
What I noticed is that when I put the red chickens on the ground I get "landing" particles. The one when I fall from a height. Maybe the placing of the nesting pens in the air has something to do with it. I've done this like To Asgaard did and the OP has hanging nesting pens like I can see on the screenshots.

**Comment by GenDeathrow** [comment] 2017-02-19 23:54
I have no idea how it would happen.. they aren't real entities. they are literally nbt data saved inside the tile entity much like an item is saved in a chest. Clients render the chickens as a fake model as an extension of the tile entity. so they are technically a block. as far as the falling particle's I did have to make them immune to falling damage because something dealing with data being saved as if they fall. I look into it again. Technically it shouldn't happen, but it is.. so its not something that jumps out as an issue.

**Comment by GenDeathrow** [comment] 2017-02-20 03:57
What type of systems is everyone running (OS)?

I wrote I had to make them immune to falling damage, really I just changed a setting to say they werent really falling.

**Comment by jk1895** [comment] 2017-02-20 09:57
I use Windows 10 64 bit.
Maybe this change helps. We will see.
Thank you for your effort.

**Comment by JoshHawley** [comment] 2017-02-23 05:34
I am having this issue as well. 
Chicken type does not seem to matter. 
Chickens were hatched in the nest, and then when grown up moved with a net over to a pen. No damage.
Windows 10 64 bit.
java version 8 Update 111
I use the Curse launcher to play SkyFactory 3. 
I have not added/removed/changed/updated any mods/configs.

I see that there is a newer version of Java (Update 121). I will go install that.
I'm happy to zip up my world and/or profile directory and send it to you if you think it will help.

**Comment by MisfitBitz** [comment] 2017-02-28 18:53
Same issue here. It's so odd. 
Hatched in nests, carefully captured with the net and put in pens. On a server, my chickens are chunkloaded. Server, Java and everything is fully updated and I'm running Win 7. I managed to avoid all of the auto update to the disaster that seems to be Win 10. I'd say about half of my chickens are suffering. :( Poor things.

**Comment by GenDeathrow** [comment] 2017-04-23 18:22
ok finally have seen this issue show up on my side.. So im looking into whats causing it it. I believe it is because the chickens think they are taking fall damage.. first time I have ever seen this on my dev branch. not sure why it happens at random.

**Comment by GenDeathrow** [comment] 2017-05-11 18:09
I pushed out an new update the other day. I was wondering if you guys still get this issue. Im hoping the current changes have fixed it. I cant reliable get this to trigger my side. also its possible previous chickens before the update may still be bugged after the update. New update is the latest beta build

**Comment by GenDeathrow** [comment] 2017-05-21 05:42
Im going to close this for now.. unless some one reports it again.

**Comment by ceiphas** [comment] 2017-05-25 11:21
I still have the problem with the most current version in my sky factory 3 (i updated this mod by hand).

it seems as if the chicken die some blocks away from the pen in my mob farm (the drops always lie on the basic spikes frim tiny progressions)

the pens line the outer wall of my mob farm, so the distance is about 3 to 7 blocks

**Comment by GenDeathrow** [comment] 2017-05-25 14:20
Wait.. your telling me that your chickens are dying in the pens, but the drops are inside the mob farm? This forge or spongeforge?

**Comment by GenDeathrow** [comment] 2017-05-25 14:33
Nvm your a genius.. some how the chickens are still moving around even though their ai is turned off and they are looked to the nesting pen..
 great.. will get this fixed.. Your comment made me check this in a different way.

**Comment by GenDeathrow** [comment] 2017-05-25 17:35
https://github.com/GenDeathrow/Hatchery/issues/86 Referencing this here.. Some one noticed sounds coming for another area, this is prolly due to the same reason.. that an chicken was in and wasn't in the world walking around.

**Comment by GenDeathrow** [comment] 2017-05-25 17:39
Well it took long enough but I think I have a fix for this. going to do some testing tonight and get an update out. 

@ceiphas @lordtazman @jk1895 @JoshHawley @MisfitBitz  THank you all for helping with this. I hate that this went on for as long as it did. but at least I know why  its happening.

**Comment by ceiphas** [comment] 2017-05-25 22:18
yay, i helped :-)

**Comment by GenDeathrow** [comment] 2017-05-28 14:35
Ill be getting an update out next day or so.. but you will have to manually update since SF3 may not be receiving anymore updates

**Comment by GenDeathrow** [comment] 2017-06-07 06:30
should be fixed in latest beta build.. closing for now

**Closed by GenDeathrow** 2017-06-07 06:30 UTC
Labels: bug

**Comment by jk1895** [comment] 2017-06-07 07:19
Unfortunately, I can not test it because I stopped playing a while ago.
Nevertheless thank you for your efforts. I will definitely play again. Sometime.
Greetings

**Comment by ceiphas** [comment] 2017-06-14 05:29
i tested it with putting out a bucket of witchwater around the pens. 

i got no chicken dying sounds, i think it's fixed
