### ISSUE TITLE
Animal Net Dupe

### ISSUE THREAD

**Issue by Y0ungSandwich** [GenDeathrow/Hatchery#23] opened 2016-12-18 20:11 UTC
This doesn't seem like an issue with your mod but maybe with sponge servers. Can not duplicate in SSP.

After placing an animal with the net, anywhere, it doesn't clear the animal net. You can now right click and duplicate the last grabbed chicken. Anything you could possibly look into?

**Comment by GenDeathrow** [comment] 2016-12-19 01:09
Strange, it could be sponge, cause I have seen server not dupe chickens. Not sure what on sponge could be causing it. I will look into though.

**Comment by Cuppycake** [comment] 2016-12-19 02:06
Thanks so much.  At the very least maybe even allowing other mod items to place the chickens in the nest? Like the golden lasso from EU2 comes to mind.  

I did try to reproduce this in SSP and a standard Forge server.  Only happens on our sponge server.

**Comment by GenDeathrow** [comment] 2016-12-19 04:42
Thanks for testing, adding in other items like the lasso was on the list, I just hadn't had the time. plus I got some bug fixing that has to get out. I do appreciate you testing it out. I have not run sponge  before.  If there is a way to make both happy I will.

**Comment by Cuppycake** [comment] 2016-12-19 14:07
That would be amazing. Some authors just aren't caring at all about Sponge and its really putting a damper on some communities. Thanks for the positive outlook!

**Comment by GenDeathrow** [comment] 2016-12-21 08:56
I fixed something on my end. that my have been causing the dupe. I didn't get a look at it in sponge yet. but I think the fix for something else may have fixed this issue as well. please get back with me ASAP

**Comment by Cuppycake** [comment] 2016-12-21 11:17
Great I'll update and test today after work.

**Comment by GenDeathrow** [comment] 2016-12-21 17:36
I hope I unintentionally fixed it.. I realized the nets weren't dumping the entity from its nbt data. In forge you cant spawn to entities with the same ID number, but I bet sponge just gives it a new id.

**Comment by Cuppycake** [comment] 2016-12-21 20:42
Unfortunately it is still duping the chickens

**Comment by GenDeathrow** [comment] 2016-12-21 23:25
well.. that just makes zero sense, can you send me a video of it happening? "ShareX" < good program for that.  make sure to show tooltip of the item before and after placing/duping. also make sure your not in creative / OP.. although I doubt those are doing it. 

I not completely sure whats happening now. I am deleting the data after the chicken is placed.  so it shouldn't dupe.

**Comment by Cuppycake** [comment] 2016-12-22 00:33
Sure I'll get that to you after work tomorrow.  Away from my pc for the night.

**Comment by Cuppycake** [comment] 2016-12-22 21:31
Again tried it without sponge and it worked fine.  Here it is with sponge.  

http://mechandmagic.com/animalnet.mp4

**Comment by Cuppycake** [comment] 2016-12-29 17:29
Also in addition to the golden lasso I believe soul vials from EnderIO might be a nice additional item to place chickens.

**Comment by GenDeathrow** [comment] 2016-12-31 02:49
I'm not sure what sponge/forge are doing together, cause I am using the correct method to remove the entity from the item via NBT removal, So it shouldn't work.  Its very confusing

**Comment by Broklyndatroll** [comment] 2017-01-03 17:22
I am also having this same issue on the SF3 server our Network has set up. I used an Animal Net to pick up one of the Nether Chickens I liberated via Golden Lasso from Hell, and placed it into a Nesting Pen. But now my Net is basically functioning as a Wand of Nether Chickens. Not only is this a Duping issue, but unless I make multiple Nets, there is no way to place higher stat/generation chickens into the Nesting Pens to further my breeding. 

Loving the implementation of the Agricraft breeding model to Chickens though!

**Comment by GenDeathrow** [comment] 2017-01-09 08:37
@Broklyndatroll Sponge Server?

**Comment by GenDeathrow** [comment] 2017-01-16 23:50
Guys I have been talking with about 5-6 other mod dev's, They are all having issues with Sponge. TBH I cant support something that is obviously not my fault. I kept open mind about it at first, but something isn't right on their end. 

My animal net code isn't anymore clear on what it's doing.. it places a chicken and deletes the data from the net via nbt. Even built into forge is a way to prevent entities with the same UUID being place. But Sponge seems to be ignoring it. 

The moment they get this problems sorted out I will re-look at these issue.

**Comment by Cuppycake** [comment] 2017-01-16 23:58
Understandable.  You've been a great help and support with bug fixes so far so thank you for that.  Any chance of looking at how EU or EnderIO might do it?  Having no issues with any other mod with a net type of item.

**Comment by GenDeathrow** [comment] 2017-01-17 01:49
I'll look again and we will see. But Ive got a couple of other projects that need attention.

**Comment by Callum-MM** [comment] 2017-01-21 19:34
I know its not the best but i have come up with a temporary solution to your issue. We were having the same issue on our server and i thought of using minetweaker to fix it until sponge get their act together.

Very simply, If you add,

recipes.addShapeless(<hatchery:animalnet>, [<hatchery:animalnet>]);

![animalnet](https://cloud.githubusercontent.com/assets/14040343/22177151/89ad145e-e010-11e6-81f6-f2716a5cab12.png)

to a minetweaker script it lets you craft a fresh animal net from the one with the extra NBT data in it. It's obviously not meant to be used as a permenant solution to the problem but it lets you use the hatchery mod and sponge together without having to craft a new animal net every time you want to move a chicken xD

**Comment by GenDeathrow** [comment] 2017-01-24 19:01
Was fixed via Sponge.

https://github.com/SpongePowered/SpongeCommon/commit/4648e4af32f68b07690df05d5446a5b74b99f2b2

**Closed** 2017-01-24 19:01 UTC
Labels: bug, Sponge, wontfix

**Comment by Y0ungSandwich** [comment] 2017-01-24 19:03
Watching and saw, thank you for your help!

**Comment by GenDeathrow** [comment] 2017-01-24 19:07
not that I did much, but atleast it got looked at.

**Comment by ktole1999** [comment] 2017-04-02 20:33
anyone know what sponge version this was fixed in?
